spring:
  application:
    name: vehicle-rest-service-axon

server:
  port: 8085

axon:
  axonserver:
    servers:
      ${AXON_SERVER:localhost}:8124

logging:
  level:
    org:
      mkralik:
        learning:
          axon:
            microservices:
              cinema: debug
          lra:
            axon: debug
